1.Write a python program to add below matrices
X = [[12,7,3],
[4 ,5,6],
[7 ,8,9]]
Y = [[5,8,1],
[6,7,3],
[4,5,9]]

In [2]:
import numpy as np
x = np.array([[12,7,3],[4,5,6],[7,8,9]])
y = np.array([[5,8,1],[6,7,3],[4,5,9]])
result = np.add(x, y)
print("Addition of matrices x and y is : \n")
print(result)

Addition of matrices x and y is : 

[[17 15  4]
 [10 12  9]
 [11 13 18]]


2.Write a program to perform scalar multiplication of matrix and a number
X = [[12,7,3],
[4 ,5,6],
[7 ,8,9]]
Y = 9

In [3]:
x = np.array([[12,7,3],[4,5,6],[7,8,9]])
y = 9
print("scalar multiplication of matrix and a number : \n ")
print(np.dot(x,y))

scalar multiplication of matrix and a number : 
 
[[108  63  27]
 [ 36  45  54]
 [ 63  72  81]]


3.Write a program to perform multiplication of given matrix and vector
X = [[ 5, 1 ,3], [ 1, 1 ,1], [ 1, 2 ,1]], Y = [1, 2, 3]

In [4]:
x = np.array([[ 5, 1 ,3], [ 1, 1 ,1], [ 1, 2 ,1]])
y = [1,2,3]
print("Multiplication of vector and matrix : \n ")
print(np.dot(x,y))

Multiplication of vector and matrix : 
 
[16  6  8]


4.Write a program to multiply matrices in problem 1

In [5]:
x = np.array([[12,7,3],[4,5,6],[7,8,9]])
y = np.array([[5,8,1],[6,7,3],[4,5,9]])
print("Multiplication of two matrices : \n ")
print(np.dot(x,y))

Multiplication of two matrices : 
 
[[114 160  60]
 [ 74  97  73]
 [119 157 112]]


5.Write a program to find inverse matrix of matrix X in problem 1 

In [6]:
x = np.array([[12,7,3],[4,5,6],[7,8,9]])
print("Inverse of matrix : \n")
print(np.linalg.inv(x))
#print(np.linalg.det(x))

Inverse of matrix : 

[[  1.          13.          -9.        ]
 [ -2.         -29.          20.        ]
 [  1.          15.66666667 -10.66666667]]
-2.9999999999999982


6.Write a program to find transpose matrix of matrix Y in problem 1

In [7]:
y = np.array([[5,8,1],[6,7,3],[4,5,9]])
print("Transpose of matrix : \n")
print(y.transpose())
#print(y.T)

Transpose of matrix : 

[[5 6 4]
 [8 7 5]
 [1 3 9]]
